# Generated by Django 2.1.1 on 2019-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=5000)),
                ('person', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('oriImage', models.CharField(max_length=1000)),
                ('oriKeywords', models.CharField(max_length=200)),
                ('oriScores', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=5000)),
                ('person', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('oriImage', models.CharField(max_length=1000)),
                ('oriKeywords', models.CharField(max_length=200)),
                ('oriScores', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
